### PR TITLE
Nullish Coalescing Operator to ES5 format (compiled)

### PR DESCRIPTION
**Pull request by UnleashedMySelf**
Compiled version:
image

### CODE REVIEW

**Comment by UnleashedMySelf** [comment]
@mattkingshott please review it

**Comment by mattkingshott** [comment]
Please resubmit without builds. I have no idea if they contain custom code. 

Also void 0 is not considered good JS.

**Comment by UnleashedMySelf** [comment]
@mattkingshott This is es5 babel converter, but if you don’t like it, we can replace it with ||. Tests passed

**Comment by mattkingshott** [comment]
Please do and resubmit. 👍🏻

**Pull request closed without merging**
